"""Train GeoRT FK model without SAPIEN dependency.

Uses URDF FK data (generated by regenerate_fk_data.py) to train a neural FK model
that maps joint angles -> fingertip positions + PIP joint positions (6D per finger).

Usage:
    python scripts/geort/train_fk.py --hand orca_right --n-output 6 --epochs 200
"""
import os
import sys
import argparse
import math
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.join(_SCRIPT_DIR, "..", "..")
_GEORT_ROOT = os.path.join(_PROJECT_ROOT, "third_party", "GeoRT")
sys.path.insert(0, _GEORT_ROOT)

from geort.utils.config_utils import get_config
from geort.model import FKModel
from geort.formatter import HandFormatter


class FKDataset(Dataset):
    """Load qpos + keypoint (+ optional pip_joint) from npz."""

    def __init__(self, npz_path, keypoint_names, n_output_per_finger=3):
        data = np.load(npz_path, allow_pickle=True)
        self.qpos = data["qpos"].astype(np.float32)
        keypoints = data["keypoint"].item()
        pip_joints = data["pip_joint"].item() if "pip_joint" in data else None

        targets = []
        for name in keypoint_names:
            tip = keypoints[name][:, :3]
            if n_output_per_finger > 3 and pip_joints is not None:
                pip = pip_joints[name][:, :3]
                targets.append(np.concatenate([tip, pip], axis=-1).astype(np.float32))
            else:
                targets.append(tip.astype(np.float32))
        self.targets = np.stack(targets, axis=1)  # [N, n_fingers, n_output]

    def __len__(self):
        return len(self.qpos)

    def __getitem__(self, idx):
        return self.qpos[idx], self.targets[idx]


def main():
    parser = argparse.ArgumentParser(description="Train GeoRT FK model (no SAPIEN)")
    parser.add_argument("--hand", type=str, required=True)
    parser.add_argument("--n-output", type=int, default=6,
                        help="Output dims per finger (3=tip only, 6=tip+PIP)")
    parser.add_argument("--epochs", type=int, default=200)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=5e-4)
    args = parser.parse_args()

    os.chdir(_GEORT_ROOT)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")

    config = get_config(args.hand)
    joint_order = config["joint_order"]

    keypoint_joints = []
    keypoint_links = []
    for info in config["fingertip_link"]:
        keypoint_joints.append([joint_order.index(j) for j in info["joint"]])
        keypoint_links.append(info["link"])

    # Joint limits for normalization
    import xml.etree.ElementTree as ET
    urdf_path = os.path.join(_GEORT_ROOT, config["urdf_path"].lstrip("./"))
    tree = ET.parse(urdf_path)
    root = tree.getroot()
    urdf_limits = {}
    for joint in root.findall("joint"):
        name = joint.get("name")
        limit = joint.find("limit")
        if limit is not None and joint.get("type") == "revolute":
            urdf_limits[name] = (float(limit.get("lower")), float(limit.get("upper")))

    joint_lower = np.array([urdf_limits[j][0] for j in joint_order], dtype=np.float32)
    joint_upper = np.array([urdf_limits[j][1] for j in joint_order], dtype=np.float32)
    normalizer = HandFormatter(joint_lower, joint_upper)

    npz_path = f"data/{config['name']}.npz"
    dataset = FKDataset(npz_path, keypoint_links, n_output_per_finger=args.n_output)
    dataloader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True)

    print(f"Dataset: {len(dataset)} samples, target shape per sample: {dataset.targets.shape[1:]}")
    print(f"Keypoint joints: {keypoint_joints}")

    fk_model = FKModel(keypoint_joints=keypoint_joints, n_output_per_finger=args.n_output).to(device)
    fk_optim = optim.Adam(fk_model.parameters(), lr=args.lr)
    criterion = nn.MSELoss()

    ckpt_path = f"checkpoint/fk_model_{config['name']}.pth"
    os.makedirs("checkpoint", exist_ok=True)

    print(f"\nTraining FK model ({args.epochs} epochs, {args.n_output}D output per finger)...")
    for epoch in range(args.epochs):
        total_loss = 0
        n_batches = 0
        for qpos, target in dataloader:
            qpos = qpos.to(device)
            target = target.to(device)
            qpos_norm = normalizer.normalize_torch(qpos)
            pred = fk_model(qpos_norm)

            loss = criterion(pred, target)
            fk_optim.zero_grad()
            loss.backward()
            fk_optim.step()

            total_loss += loss.item()
            n_batches += 1

        avg_loss = total_loss / n_batches
        if epoch % 10 == 0 or epoch == args.epochs - 1:
            avg_err_mm = math.sqrt(avg_loss) * 1000
            print(f"Epoch {epoch:3d} | MSE: {avg_loss:.6e} | RMSE: {avg_err_mm:.2f}mm")

    torch.save(fk_model.state_dict(), ckpt_path)
    print(f"\nSaved FK model to {ckpt_path}")

    # Quick validation
    fk_model.eval()
    with torch.no_grad():
        indices = list(range(min(100, len(dataset))))
        qpos_batch = torch.from_numpy(np.stack([dataset[i][0] for i in indices])).to(device)
        target_batch = torch.from_numpy(np.stack([dataset[i][1] for i in indices])).to(device)
        qpos_norm = normalizer.normalize_torch(qpos_batch)
        pred_batch = fk_model(qpos_norm)
        # Per-finger error on tip portion (first 3 dims)
        tip_err = (pred_batch[:, :, :3] - target_batch[:, :, :3]).norm(dim=-1).mean(dim=0)
        finger_names = [info["name"] for info in config["fingertip_link"]]
        print("\nValidation (100 samples):")
        for i, name in enumerate(finger_names):
            print(f"  {name} tip: {tip_err[i].item()*1000:.2f}mm")
        if args.n_output > 3:
            pip_err = (pred_batch[:, :, 3:] - target_batch[:, :, 3:]).norm(dim=-1).mean(dim=0)
            for i, name in enumerate(finger_names):
                print(f"  {name} pip: {pip_err[i].item()*1000:.2f}mm")


if __name__ == "__main__":
    main()
